# protto templates
# ponytail: context-aware starter content for docs, agents, commands, rules.
# This is not generic stub filler; it uses what protto already detected.

# Helpers to avoid repetition
tmpl_agent_name() { echo "reviewer"; }
tmpl_command_name() { echo "review"; }
tmpl_rule_name() { echo "baseline"; }
tmpl_decision_name() { echo "2026-07-27-baseline"; }

# Generate docs/decisions.md — one active decision the user can edit.
gen_docs_decisions() {
  local title stack
  title=$(detect_title)
  stack=$(detect_stack_name)
  cat > docs/decisions.md <<EOF
# Decisions Log

## $(tmpl_decision_name)
- **Context**: Project $title initialized with protto.
- **Decision**: Use $stack as the primary stack.
- **Consequences**: Build/test commands were detected from existing files.
- **Status**: active
- **Date**: $(date +%Y-%m-%d)

## Next Decision Needed
- What is the first invariant we want to enforce in CI?
EOF
}

# Generate .claude/agents/reviewer.md and .opencode/agents/reviewer.md
# Both agents get the same agent definition; paths are already scoped.
gen_agent_reviewer() {
  local test_cmd
  test_cmd=$(detect_test_command)
  cat > .claude/agents/reviewer.md <<EOF
# Code Reviewer

Role: critical reviewer. Run before committing any non-trivial change.

## Tools
- file, search, terminal

## Instructions
1. Read the diff with \`git diff --stat\` and \`git diff\`.
2. Check: correctness, edge cases, test coverage, and whether the change follows the project conventions in CLAUDE.md.
3. Run \`$test_cmd\` if tests exist.
4. Respond with a short verdict: APPROVE, REQUEST CHANGES, or NEEDS TESTS.
EOF
  cat > .opencode/agents/reviewer.md <<EOF
# Code Reviewer

Role: critical reviewer. Run before committing any non-trivial change.

## Tools
- file, search, terminal

## Instructions
1. Read the diff with \`git diff --stat\` and \`git diff\`.
2. Check: correctness, edge cases, test coverage, and whether the change follows the project conventions in AGENTS.md.
3. Run \`$test_cmd\` if tests exist.
4. Respond with a short verdict: APPROVE, REQUEST CHANGES, or NEEDS TESTS.
EOF
}

# Generate a slash command for running a focused review.
gen_command_review() {
  cat > .claude/commands/review.md <<EOF
# /review

Run the Code Reviewer agent on the current working changes.

## Steps
1. Read \`CLAUDE.md\`, \`docs/architecture/\`, and \`docs/context.md\`.
2. Run \`git diff --stat\` and \`git diff\`.
3. Delegate to \`.claude/agents/reviewer.md\` with the diff context.
4. Output: bullet list of blockers, risks, and one-line approval verdict.
EOF
  cat > .opencode/commands/review.md <<EOF
# /review

Run the Code Reviewer agent on the current working changes.

## Steps
1. Read \`AGENTS.md\`, \`docs/architecture/\`, and \`docs/context.md\`.
2. Run \`git diff --stat\` and \`git diff\`.
3. Delegate to \`.opencode/agents/reviewer.md\` with the diff context.
4. Output: bullet list of blockers, risks, and one-line approval verdict.
EOF
}

# Generate a scoped rule for the lib/ or src/ directory.
gen_rule_baseline() {
  cat > .claude/rules/baseline.md <<EOF
# Baseline Rules

Applies to: \`**/*.{sh,py,js,ts,rs,go}\`

- Keep functions short and single-purpose.
- Prefer explicit error handling over silent failures.
- Add a test or ad-hoc verification script for any non-trivial change.
- Update \`docs/context.md\` when the change affects architecture or decisions.
EOF
  cat > .opencode/rules/baseline.md <<EOF
# Baseline Rules

Applies to: \`**/*.{sh,py,js,ts,rs,go}\`

- Keep functions short and single-purpose.
- Prefer explicit error handling over silent failures.
- Add a test or ad-hoc verification script for any non-trivial change.
- Update \`docs/context.md\` when the change affects architecture or decisions.
EOF
}

# Generate docs/architecture/index.md starter content based on detected stack.
gen_docs_architecture() {
  local title stack build test lint arch
  title=$(detect_title)
  stack=$(detect_stack_name)
  build=$(detect_build_command)
  test=$(detect_test_command)
  lint=$(detect_lint_command)
  arch=$(detect_architecture)

  cat > docs/architecture/index.md <<EOF
# Architecture

> Project: $title | Stack: $stack | Generated by protto on $(date +%Y-%m-%d).

## Overview
Start with one paragraph describing what $title does and who uses it.

## Build & Test
- Build: \`$build\`
- Test: \`$test\`
- Lint: \`$lint\`

## Structure
$(detect_architecture)

## Entrypoints
List the main entrypoints and how data flows between them.

## Decisions
See \`docs/decisions.md\`.

## Context
See \`docs/context.md\`.
EOF
}

# Generate docs/context.md starter.
gen_docs_context() {
  cat > docs/context.md <<EOF
# Context

> Current phase, latest decisions, and next steps. Keep it short.

## Phase
Initial setup with protto.

## Latest Decisions
See \`docs/decisions.md\`.

## Next Steps
- [ ] Confirm the detected build/test commands in CLAUDE.md / AGENTS.md.
- [ ] Fill the Overview in \`docs/architecture/\`.
- [ ] Run \`/speckit-specify\` — output lands in \`docs/specs/\`.
- [ ] Run ui-ux pro max — output lands in \`docs/design-system/\`.
- [ ] Run \`protto analyze\` to import or bootstrap the knowledge graph.
EOF
}

# Generate docs/specs/index.md — placeholder for speckit output.
gen_docs_specs() {
  cat > docs/specs/index.md <<EOF
# Specs

> Feature specifications and implementation plans. Generated by speckit.

## How to Use
Run \`/speckit-specify\` to create a feature spec. Output lands in \`docs/specs/<feature-name>/\`.
Run \`/speckit-plan\` for the implementation plan. Run \`/speckit-converge\` to assess code against spec.

## Design System
UI/UX specifications and visual direction live in \`docs/design-system/\`.
EOF
}

# Generate docs/design-system/index.md — placeholder for ui-ux output.
gen_docs_design_system() {
  cat > docs/design-system/index.md <<EOF
# Design System

> UI/UX specifications, visual direction, and component library. Generated by ui-ux pro max or Open Design.

## How to Use
Run ui-ux pro max or \`/open-design-integration\` to generate design specs. Output lands here.

## See Also
- \`docs/specs/\` — feature specs that reference this design system.
- \`docs/architecture/\` — how the design system fits into the project architecture.
EOF
}

# Wrapper that generates all contextual content.
gen_contextual_content() {
  gen_docs_decisions
  gen_docs_architecture
  gen_docs_context
  gen_docs_specs
  gen_docs_design_system
  gen_agent_reviewer
  gen_command_review
  gen_rule_baseline
}
